name: Run .NET Tests

on:
  pull_request:
    branches: [ main ] 
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore backend/Exchanger.Tests/Exchanger.Tests.csproj

      - name: Build solution
        run: dotnet build backend/Exchanger.Tests/Exchanger.Tests.csproj --no-restore

      - name: Run tests
        run: dotnet test backend/Exchanger.Tests/Exchanger.Tests.csproj --no-build --verbosity normal

